### ISSUE TITLE
[Bug] Users with VRChat Team trust rank spamming friend

### ISSUE THREAD

**Issue by IncompatibleW** [Natsumi-sama/VRCX#10]
Users that are on the VRChat Team will periodically all spam the friend log with rank changes.
![image](https://user-images.githubusercontent.com/20784222/124508096-37c20c00-dd9d-11eb-88e1-71f584a7c696.png)

**Comment by Natsumi-sama** [comment]
https://github.com/Natsumi-sama/VRCX/issues/9#issuecomment-875329119
