### ISSUE TITLE
Friend log notifies about non-existent entries

### ISSUE THREAD

**Issue by IncompatibleW** [Natsumi-sama/VRCX#11]
Same issue as #9 still occurring on a fresh install of the latest release.

**Comment by IncompatibleW** [comment]
Re-encoded video to hopefully work since Github didnt like the lat one. 

https://user-images.githubusercontent.com/20784222/127083302-c5aef3a6-33a0-4fc3-8b4c-4b3962e5d3b2.mp4

**Comment by Natsumi-sama** [comment]
Should be fixed with this https://github.com/Natsumi-sama/VRCX/commit/455d8e70ae885d0ee36379e47dfc708a800c8350
