### ISSUE TITLE
[Bug] API Requests... and other things slows down after time

### ISSUE THREAD

**Issue by Provini** [Natsumi-sama/VRCX#12]
I have no idea what's causing this and it may be isolated to me, but VRCX has slowed a lot down recently, getting worse with how long it's been open (or since I clear it's cache). A list of things affected can be:

- Fetching Online/Offline statuses
- (XS)Overlay Notifications
- Portal Drop Notifications
- Retrieving/Sending Invites. (Inv Requests or inviting myself can take over a minute to send)
- Replacing wrld/usr id with their actual name
- Fetching Instance Lists
- Possibly World/Avatar Changes
...pretty much everything that can change

Someone noted it can be a IPv6 issue but still occurs with IPv6 disabled.

It seemed to do better after clearing out the AppData VRCX folder completely, but after a couple it days of it running, the slowdown is noticeable again.

**Comment by Natsumi-sama** [comment]
Hmmm to me it sounds like API requests are timing out, but resetting the program shouldn't make any difference if that's the case. And cache gets reset on program restart. Could try press `Ctrl + Shift + I` and paste this in the console `$app.debugWebRequests = true;` I'm not sure if seeing when the web requests complete will help you but it might.

**Comment by Provini** [comment]
It recently decided to stop for whatever reason, about a day after reporting and hasn't happened since. I'll close for now.
