### ISSUE TITLE
launch.exe doesn't exist in VRChat versions <= 1078

### ISSUE THREAD

**Issue by loukylor** [Natsumi-sama/VRCX#2]
The [current fallback for launching the game](https://github.com/Natsumi-sama/VRCX/blob/PyPyDanceCompanion/AppApi.cs#L152) and [determining the location of the UserData folder](https://github.com/Natsumi-sama/VRCX/blob/PyPyDanceCompanion/LiteDB.cs#L65) relies on the existence of launch.exe, which in VRChat versions less than or equal to 1078 it does not exist. Instead, launch.exe is launch.bat.

**Comment by Natsumi-sama** [comment]
Yea I had gotten ahead of myself completely forgotten about that, oh well release should be soon enough.

**Comment by loukylor** [comment]
Yeaaaa, I hurriedly updated a bunch of my mods expecting it to come out the same day, but its been like 2 days so who know.
