### ISSUE TITLE
"CefSharp.Core.Runtime.dll' or one of its dependencies not found"

### ISSUE THREAD

**Issue by HartLeeKonnor** [Natsumi-sama/VRCX#20]
![Screenshot 2021-10-18 042935](https://user-images.githubusercontent.com/76974935/137706171-de5397b8-f1f9-4027-8ea7-45179ad8b599.png)
I'm not sure what this means.

**Comment by Natsumi-sama** [comment]
Try install:
https://aka.ms/vs/16/release/vc_redist.x64.exe
