### ISSUE TITLE
Swapping account leads to mass unfriend

### ISSUE THREAD

**Issue by MinerSpark** [Natsumi-sama/VRCX#24]
Swapping account shows me unfriending all the friends from the preivous account, I run 2 vrcx's and I even created 2 seprate vrcx installs and the issue still occures, Is there a way i can manually change the DB location and manually config that?
![cuteighosty](https://user-images.githubusercontent.com/22899721/150845002-7184cc2c-5732-4bee-bd6e-775af6b55f35.gif)

**Comment by Natsumi-sama** [comment]
It is known and will be fixed next release.
