### ISSUE TITLE
Feed: checking avatar details/author via expanded avatar picture returns an error

### ISSUE THREAD

**Issue by Asovrix** [Natsumi-sama/VRCX#26]
Steps to reproduce:
1. Select any Avatar change event in Feed tab (top one) and expand it.
2. Click on any of the two thumbnails that appear should show a larger version of avatar picture.
3. Clicking on it should show avatar details window, but instead in 100% of cases "Sorry, the author is unknown" notification appears instead.
![VRCX_2022-02-02_00-08-35](https://user-images.githubusercontent.com/44006686/152067114-38c51c22-ace2-454d-bd99-754552aeeb54.png)

Clicking on avatar name that is visible without expanding feed works correctly.
![VRCX_2022-02-02_00-08-56](https://user-images.githubusercontent.com/44006686/152067166-92a70e8b-2672-4f27-b0f1-859257f19665.png)
![VRCX_2022-02-02_00-09-13](https://user-images.githubusercontent.com/44006686/152067173-38c0ee77-2051-42d6-ac71-5cbabb6eaed1.png)

Version: VRCX.PyPyDance.Companion 2022.01.26 (2022-01-25 22:29:09)

**Comment by Natsumi-sama** [comment]
ah yes I also noticed and fixed this one 👍
