### ISSUE TITLE
Does this project stand with Ukraine?

### ISSUE THREAD

**Issue by Arefu** [Natsumi-sama/VRCX#29]
🇺🇦🇺🇦🇺🇦🇺🇦?

**Comment by Arefu** [comment]
I think #27 talks about this a little

**Comment by j-vanolst** [comment]
> I think #27 talks about this a little

Maybe they talk about it a little, but nowhere near enough imo

**Comment by Arefu** [comment]
This truly is an issue for the master branch, do you not agree @Natsumi-sama

**Comment by DubyaDude** [comment]
its kinda far to just be next to it, airplane tickets are expensive rn

**Comment by Arefu** [comment]
> its kinda far to be next to it, airplane tickets are expensive rn

Please be serious, I don't want to use communist software that deals with the bad guys.
