### ISSUE TITLE
[BUG] Auto-cached worlds tend to kick you back to home

### ISSUE THREAD

**Issue by SalbugVR** [Natsumi-sama/VRCX#3]
I've noticed that since this VRCX update some worlds that were cached from an invite or VIP world change have a tendency to go through the loading screen twice before dropping me back in my homeworld.

**Comment by Natsumi-sama** [comment]
Yea I'm having the bug too and I'm currently in the process of figuring it out.

**Comment by SalbugVR** [comment]
> Yea I'm having the bug too and I'm currently in the process of figuring it out.

I see. Have to do some more testing, but tried one test of caching a large world and going into it while it was processing and the issue came up for me then, but I was able to get into the world when I tried loading it again. This is odd because when I came across the issue before I was unable to go to any of the worlds affected by this without first clearing my cache.

**Comment by Natsumi-sama** [comment]
Hopefully fixed now, maybe.
