### ISSUE TITLE
Manage group invite requests

### ISSUE THREAD

**Issue by GenesisAria** [Natsumi-sama/VRCX#36]
It's a little troublesome to have to still go to the website to manage group invite requests.  Even though the notifications are in the client, having a way to accept them would be nice.

**Comment by Myrkie** [comment]
are you asking to accept invites in vrcx to join in vrc?

**Comment by GenesisAria** [comment]
![ComfyUIupscale_2453 jpg (2023-10-05_01-39-15)](https://github.com/Natsumi-sama/VRCX/assets/25147974/ca73f450-c653-44c1-adb0-4a26fea4e501)

**Comment by Myrkie** [comment]
> ![ComfyUIupscale_2453 jpg (2023-10-05_01-39-15)](https://user-images.githubusercontent.com/25147974/272837577-ca73f450-c653-44c1-adb0-4a26fea4e501.png)

should exist, make sure you are on nightly build.

**Comment by GenesisAria** [comment]
I am on latest nightly build, i see no means of accepting.

**Comment by ScruffyRules** [comment]
![image](https://github.com/Natsumi-sama/VRCX/assets/5356779/c6ebfe77-ba51-4dc6-a8d5-744d47244f8c)

**Comment by GenesisAria** [comment]
oh, then we have an issue of window frame, cuz the size i usually have it at actually hides that.

**Comment by Myrkie** [comment]
> ![image](https://user-images.githubusercontent.com/5356779/272839176-c6ebfe77-ba51-4dc6-a8d5-744d47244f8c.png)

beat me to it fu

**Comment by Myrkie** [comment]
> oh, then we have an issue of window frame, cuz the size i usually have it at actually hides that. no wonder i never saw it.

in appearance change width 
![image](https://github.com/Natsumi-sama/VRCX/assets/20288698/cad25fe9-46eb-4f64-a819-73cd67ee4d44)

**Comment by ScruffyRules** [comment]
> > ![image](https://user-images.githubusercontent.com/5356779/272839176-c6ebfe77-ba51-4dc6-a8d5-744d47244f8c.png)
> 
> beat me to it fu

gottem

**Comment by GenesisAria** [comment]
> > oh, then we have an issue of window frame, cuz the size i usually have it at actually hides that. no wonder i never saw it.
> 
> in appearance change width ![image](https://user-images.githubusercontent.com/20288698/272839752-cad25fe9-46eb-4f64-a819-73cd67ee4d44.png)

that sorta fixes it... but that should move those buttons over with, and having a tab in the group for it would be great too.
