### ISSUE TITLE
[BUG] VRCX attempts to auto-cache private worlds, loading in tends to hang

### ISSUE THREAD

**Issue by SalbugVR** [Natsumi-sama/VRCX#4]
Had a few times the other night where as I got an invite to a friend's WIP world that's still private, I noticed VRCX was in the process of caching it. When I tried to join the instance, it hangsed for an unusually long time during the scene transition. It doesn't seem to happen all the time, a bit inconsistent really but it has happened so I figured I'd raise an issue about it just in case. I feel like VRCX should not be able to attempt to cache worlds that are private / unlisted as it seems that can cause issues.

**Comment by Natsumi-sama** [comment]
I think this issue is unrelated to the fact that the world was private but a general VRChat bug I have heard of people having with a black screen occurring for a long time after the map finishes loading. Either that or making changes to VRChat's cache while it's in use making it mad.
