### ISSUE TITLE
Updating to [VRCX 2021.06.02] not working

### ISSUE THREAD

**Issue by SalbugVR** [Natsumi-sama/VRCX#5]
Every time I try to update the files in my VRCX folder with [VRCX 2021.06.02] it doesn't update like it should and still has me on [VRCX 2021.05.26.1] instead. I tried extracting the newest version to its own folder but every time I try to launch it I'm greeted with a blank window as seen below.

![image](https://user-images.githubusercontent.com/24326270/120397373-dc17e500-c2fd-11eb-85b6-f11057edb996.png)

**Comment by Natsumi-sama** [comment]
Whoops that's what I get for not testing, thanks should be fixed now.

**Comment by SalbugVR** [comment]
We're good now!
![image](https://user-images.githubusercontent.com/24326270/120398862-9b6d9b00-c300-11eb-9519-bbfacd77b63e.png)
