### ISSUE TITLE
[BUG] Favorites tab is non-functioning

### ISSUE THREAD

**Issue by SalbugVR** [Natsumi-sama/VRCX#6]
Whenever I click on 'favorite' to check on VIPs or favorite avatars, the page does not open. Instead, the page that was already open prior remains open.

**Comment by Natsumi-sama** [comment]
Was a dumb typo :,( https://github.com/Natsumi-sama/VRCX/commit/f81a839d78e22594025bbca3d910dc98ed186665 fixed with hotfix release.
