### ISSUE TITLE
[Bug] Notifications tab is broken, still accessible though. Notifs showing in Moderation tab

### ISSUE THREAD

**Issue by SalbugVR** [Natsumi-sama/VRCX#7]
Basically, what the title says, this issue has broken both tabs functionality it seems.

![VRCX_qT6LFmCrE6](https://user-images.githubusercontent.com/24326270/120756570-05d73480-c4d5-11eb-8611-a098b451e67d.png)
![VRCX_zV1qG6WdWz](https://user-images.githubusercontent.com/24326270/120756574-05d73480-c4d5-11eb-844d-c2f251118aaf.png)

**Comment by Natsumi-sama** [comment]
hmmm yes I have had this bug before but was never able to replicate it, any errors in the console? Ctrl + Shift + I

**Comment by SalbugVR** [comment]
> hmmm yes I have had this bug before but was never able to replicate it, any errors in the console? Ctrl + Shift + I

![image](https://user-images.githubusercontent.com/24326270/120758237-34560f00-c4d7-11eb-9942-5cbaee872924.png)

**Comment by Natsumi-sama** [comment]
This will likely fix it https://github.com/Natsumi-sama/VRCX/commit/887793b6d4707b7888ffaabc0c08871baea8dcf4

**Comment by SalbugVR** [comment]
Restarted VRCX recently and that seems to have fixed it. Just forgot to post about that here. :v
