### ISSUE TITLE
Friend log notifies about non-existent entries

### ISSUE THREAD

**Issue by Asovrix** [Natsumi-sama/VRCX#9]
Since last update Friend Log sometimes shows a dot over icon on the left side of the window meaning there is a new entry, but there are in fact no new entries.
I mean this to clarify:
![explorer_2021-07-05_12-36-20](https://user-images.githubusercontent.com/44006686/124458757-a6976900-dd8d-11eb-81d1-c31ea1ab453c.png)

Reporting it, but I have a feeling this might be covered by https://github.com/Natsumi-sama/VRCX/commit/c6c87b53da78643be731b3d4f22b49a2b9b613ed ?

**Comment by Asovrix** [comment]
Oh yeah, that happens too:
![VRCX_2021-07-06_05-03-17](https://user-images.githubusercontent.com/44006686/124536059-8a400e80-de17-11eb-86c2-aeafe9af4507.png)

**Comment by Natsumi-sama** [comment]
Yea as expected migrating to SQLite caused a lot of things to break, hopefully will have it all fixed next release.
